### ISSUE TITLE
New Gem version?

### ISSUE THREAD

**Issue by aaronjensen** [pry/pry-coolline#22]
Hi, the current released gem version depends on an old version io-console which is problematic. Any chance of a new gem cut? Thanks!

**Comment by sethherr** [comment]
Pinging on this as well - @liaden ?

**Comment by liaden** [comment]
@sethherr Yeah, but I'll need to get readded on rubygems since my confirmation token expired.

CC: @banister

**Comment by andrehjr** [comment]
Released v0.2.6 today
