### ISSUE TITLE
Pry fails to start on Windows because of bug in coolline

### ISSUE THREAD

**Issue by jjgh** [pry/pry-coolline#31]
```
> ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]

> pry -v
Pry version 0.10.1 on Ruby 2.2.2
```

> pry

Output --> https://gist.github.com/MichaelSp/905ca6033d9d2398e4d3

Can be replicated in a irb console with:

> require 'coolline'

I also opened an issue at coolline repo: https://github.com/Mon-Ouie/coolline/issues/19

**Comment by rf-** [comment]
Based on the stack trace, this seems like it's definitely a coolline issue. Feel free to reopen if pry-coolline turns out to be involved somehow
